### ISSUE TITLE
Prepend should accept non array prepend

### ISSUE THREAD

**Issue by narthur157** [JoelRoxell/prepend-style-loader#3]
Prepend fails somewhat mysteriously if prepend is supplied with a single value instead of an array. Supporting this or giving a useful error message would be nice

**Comment by JoelRoxell** [comment]
Would this suffice? https://github.com/JoelRoxell/prepend-style-loader/pull/5/files#diff-168726dbe96b3ce427e7fedce31bb0bcR15

**Comment by JoelRoxell** [comment]
implemented #5
